# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06104739ae48d6e6b6b887fdbd9d76c28ad21f56f5f6f1259a696881941ec33dfb96a716b37a841556dabd83c80441764aa6243f6baeb4d3f006e347c85ad9e0

test:
  secret_key_base: 2c1e73be6be5de77b29f795346fdb3950bd51ce1524269f1bff0f4be6bec0e2c1b5e98f96be114208d183c02372912cccecf08848ab341055913b4bf09261145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
